---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  playbook: playbook.yml
  roles_path: roles
  ansible_verbose: false
  ansible_version: latest
  require_chef_for_busser: true

platforms:
  - name: ubuntu-16.04
    box: bento/ubuntu-16.04

suites:
  - name: default
